template: |
  ### Changes and updates in release v$RESOLVED_VERSION
  $CHANGES
  
  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'UI & User Experience'
    labels:
      - 'ui'

  - title: 'Logic & Backend'
    labels:
      - 'backend'
    exclude-labels:
      - 'core'

  - title: 'Core System Updates'
    labels:
      - 'core'

  - title: 'Installer & Deployment'
    labels:
      - 'installer'

  - title: 'Build System'
    labels:
      - 'build-system'
    # Hide build changes if they are part of a feature PR
    exclude-labels:
      - 'ui'
      - 'backend'
      - 'core'

exclude-labels:
  - 'skip-changelog'

# Convert "## Title" to "**Title**"
replacers:
  - search: '/^## (.*)$/gm'
    replace: '**$1**'